on:
  workflow_dispatch: #button for triggering action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@master
        with:
            fetch-depth: 1

      - name: Process data 
        run: make greeting #its in the make file
        